#%RAML 1.0 Library
usage:
traits:
  transactionId: !include traits/Headers-transactionId-traits.raml
  departureLocationCode: !include traits/QueryParams-DepartureLocationCode-traits.raml
  destinationLocationCode: !include traits/queryParams-DestinationLocationCode-traits.raml
